authors:
  foudamo:
    name: Mohamed Fouda        # Author name
    description: Product Manager # Author description
    avatar: "https://avatars.githubusercontent.com/u/6817956?v=4"          # Author avatar
    url: "https://github.com/foudamo"            # Author website URL
  apurvakb:
    name: Apurv Banastarker        # Author name
    description: Digital Marketing # Author description
    avatar: "https://avatars.githubusercontent.com/u/61383076?v=4"          # Author avatar
    url: "https://github.com/apurvakb"            # Author website URL
  kristinataylor:
    name: Kristina Taylor        # Author name
    description: Product Manager # Author description
    avatar: "https://avatars.githubusercontent.com/u/10520385?v=4"          # Author avatar
    url: "https://www.linkedin.com/in/kristina-taylor-48273427/"            # Author website URL